### ISSUE TITLE
Disable "Doors". Doors should have a token too, so it's better to use them as devices

### ISSUE THREAD

**Issue by vongomben** [OfficineArduinoTorino/LabAdmin#1]
Hope the tilte is self-explanatory

**Comment by xrmx** [comment]
Note to self: the idea should be that there's no such thing as doors, each door should be handled independently as are the devices. This is an opportunity to remove the _kind_ in roles and remove the duplication in methods like "can_use_device_now" and "can_open_door_now".

**Comment by xrmx** [comment]
This has been fixed in #2, closing.
