### ISSUE TITLE
Cannot delete Device user code

### ISSUE THREAD

**Issue by tommasoltrz** [OfficineArduinoTorino/LabAdmin#40]
How do I delete one of this ?

![screen shot 2017-06-14 at 12 30 53](https://user-images.githubusercontent.com/11644423/27128215-e883a098-50fd-11e7-827d-7c31276d663c.png)

There is no button for that..

**Comment by xrmx** [comment]
Have you tried selecting the row ticking the "delete" column and then saving?

**Comment by tommasoltrz** [comment]
That was easy,
thanks
